@startuml
class Foo类 {
+ field1
+ field2
}

class Bar类 {
+ field3
+ field4
}

Foo类::field1 --> Bar类::field3 :foo.field1 = bar.field3
Foo类::field2 --> Bar类::field4 : bar

newpage


left to right direction

class User类 {
  id : INTEGER
  ..
  其他id : INTEGER
}

class Email类 {
  id : INTEGER
  ..
  用户_id : INTEGER
  地址 : STRING
}

User类::id *-- Email类::用户_id : 123



@enduml
