@startuml

title 充电器适配

class Phone {
    + charging() : void
}

interface Voltage5V {
    + output5V() : void
}

class Voltage220V {
    + output220V() : void
}

class VoltageAdapter extends Voltage220V implements Voltage5V {

}



Phone .> Voltage5V


@enduml